### ISSUE TITLE
APIラッパーどうする？

### ISSUE THREAD

**Issue by sonyakun** [sonyaComunityTeam/public-discord-bot#2]
選択肢
1.discord.py
2.nextcord
3.Pycord
4.独自開発(dpy系※開発する意味ない気がする)
5.その他

**Comment by ActCelely** [comment]
pycordがいいな

**Comment by NEPTARUNE** [comment]
スラコマが実装できるやつでD.pyコードをほぼ書き換え無しで使えるやつ...
Pycordかな？

**Comment by ActCelely** [comment]
その方がいいでしょ
でも最悪discord.pyがいいな

**Comment by ActCelely** [comment]
pycord! or discord.py!
nextcordは文献（？）なさ過ぎたからpycordかdiscord.py

**Comment by ActCelely** [comment]
パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！パイコード！

**Comment by sonyakun** [comment]
スパムは禁止されています

**Comment by sonyakun** [comment]
https://docs.nextcord.dev
ちなみに確か旧RTがNextcordだった希ガス

**Comment by sonyakun** [comment]
Nextcordのコード(見本)
https://gist.github.com/sonyakun/8aa39a4bc2b44e609218fbfe9587d7e6
Pycordのコード(見本)
https://gist.github.com/sonyakun/c684a79eba27a1e47df76b54915d7bb8
僕の環境だとPycordコード合ってても動かないんだよね…

**Comment by NEPTARUNE** [comment]
Nextcordは触ったことないので僕はpycordかd.pyを要求

**Comment by NEPTARUNE** [comment]
あとnextcordの構文僕書けない

**Comment by NEPTARUNE** [comment]
> https://docs.nextcord.dev ちなみに確か旧RTがNextcordだった希ガス

RT?なにそれおいしいの？

**Comment by sonyakun** [comment]
> 

ha?

**Comment by sonyakun** [comment]
> あとnextcordの構文僕書けない

別に書き換え必要ないよ？
スラッシュコマンドのコード覚えればいい話だし

**Comment by NEPTARUNE** [comment]
けれどもnextcordはマジで一回も触ったことない

**Comment by ActCelely** [comment]
> スパムは禁止されています

スパムじゃない心の嘆きだ（？）
（すみません）

**Comment by ActCelely** [comment]
こういう風になるくらいならDiscord.pyでもいい気がするぞ

**Comment by ActCelely** [comment]
機能的にはpycordのほうがいいけど
こうやって言い争うなら
discord-ui使おう
（discord-ui - discord で UI インタラクションを送信、受信、および処理するための discord.py 拡張機能）

**Comment by ActCelely** [comment]
コマンドをまとめたりしやすいのはpycord

**Comment by ActCelely** [comment]
プレゼントto sonya
https://guide.pycord.dev/introduction

**Comment by ActCelely** [comment]
やっぱりdiscord.pyにui使ってもいいな～

**Comment by sonyakun** [comment]
ちなみにdiscord.ui(nextcord.ui)も実装済み

> やっぱりdiscord.pyにui使ってもいいな～

**Comment by sonyakun** [comment]
えっと、pycordで
どうしても動かなければ他のAPIラッパーも考える

**Comment by sonyakun** [comment]
えっと、pycordで
どうしても動かなければ他のAPIラッパーも考える
