### ISSUE TITLE
Botアカウントの作成

### ISSUE THREAD

**Issue by NEPTARUNE** [sonyaComunityTeam/public-discord-bot#6]
Botアカウントがないとコードがあっても意味ないよねってことで。
誰がBotアカウント作る？
あと付けるインテントも選ばなきゃね。

**Comment by SHUtk0405** [comment]
そこはそにゃかなぁ？僕でもいいけど....

**Comment by NEPTARUNE** [comment]
あとTOKENはどうするか問題

**Comment by NEPTARUNE** [comment]
Dev(開発版)と安定版分けたいな。
Devは運営が全員弄れて、安定版は上位運営しか弄れないとか。

**Comment by NEPTARUNE** [comment]
取り敢えずコードのテストしたいので適当なアカウント作ります。

**Comment by sonyakun** [comment]
とりあえず作るわ

**Comment by sonyakun** [comment]
作成済み
